In [1]:

# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

# 1.) Scrape the details of most viewed videos on YouTube from Wikipedia: Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos

In [2]:
driver = webdriver.Chrome("chromedriver.exe")
url="https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

driver.find_element_by_xpath("//b").click()

time.sleep(3)
records = []
for row in driver.find_elements_by_xpath("(//table[@class='wikitable sortable jquery-tablesorter'])[1]//tr")[1:-1]:
    temp = ''
    for element in row.find_elements_by_xpath(".//td"):        
        temp += element.text + '|'
    records.append(temp.split('|')[:-2])

df = pd.DataFrame(records,columns=['rank','video_name','artist','views(M)','date_uploaded'])
    
arranged_cols = ['rank','video_name','artist','date_uploaded','views(M)']
    
df.video_name = df.video_name.apply(lambda x:x[:-4].strip('"'))
df = df[arranged_cols]
df

,rank,video_name,artist,date_uploaded,views(M)
0,1.,Baby Shark Dance,Pinkfong Kids' Songs & Stories,"June 17, 2016",9.10
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.48
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",5.61
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.41
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.21
5,6.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.45
6,7.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.41
7,8.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.38
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.25
9,10.,Gangnam Style,Psy,"July 15, 2012",4.14
10,11.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.05
11,12.,Sugar,Maroon 5,"January 14, 2015",3.52
12,13.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.50
13,14.,Sorry,Justin Bieber,"October 22, 2015",3.46
14,15.,Roar,Katy Perry,"September 5, 2013",3.40
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.36
16,17.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.30
17,18.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.20
18,19.,Dark Horse,Katy Perry,"February 20, 2014",3.11
19,20.,Faded,Alan Walker,"December 3, 2015",3.11
20,21.,Girls Like You,Maroon 5,"May 31, 2018",3.09
21,22.,Shake It Off,Taylor Swift,"August 18, 2014",3.08
22,23.,Lean On,Major Lazer,"March 22, 2015",3.08
23,24.,Bailando,Enrique Iglesias,"April 11, 2014",3.07
24,25.,Let Her Go,Passenger,"July 25, 2012",3.04
25,26.,Mi Gente,J Balvin,"June 29, 2017",2.96
26,27.,Axel F,Crazy Frog,"June 16, 2009",2.92
27,28.,Perfect,Ed Sheeran,"November 9, 2017",2.92
28,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",2.90
29,30.,Hello,Adele,"October 22, 2015",2.86

# 2.) Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.

In [7]:
driver = webdriver.Chrome("chromedriver.exe")
url="https://www.bcci.tv/international/fixtures"
driver.get(url)

Date_Time =[]
Ground=[]
Test_ODI=[]
Team=[]

tm=driver.find_elements_by_xpath("//div[@class='fixture__teams']")
time.sleep(3)
for i in tm:
    if i.text is None :
        Team.append("--") 
    else:
        Team.append(i.text)

G=driver.find_elements_by_xpath("//p[@class='fixture__additional-info']/span")
time.sleep(3)
for i in G:
    if i.text is None :
        Ground.append("--") 
    else:
        Ground.append(i.text)
DT=driver.find_elements_by_xpath("//span[@class='fixture__datetime tablet-only']")
time.sleep(3)
for i in DT:
    if i.text is None :
        Date_Time.append("--") 
    else:
        Date_Time.append(i.text)
TO=driver.find_elements_by_xpath("//p[@class='fixture__additional-info']/strong")
time.sleep(3)
for i in TO:
    if i.text is None :
        Test_ODI.append("--") 
    else:
        Test_ODI.append(i.text)

In [8]:
INDIA_MATCHES =pd.DataFrame([])
INDIA_MATCHES['Team']=Team
INDIA_MATCHES['Date_Time']=Date_Time
INDIA_MATCHES['Series']=Test_ODI
INDIA_MATCHES['Ground']=Ground
INDIA_MATCHES

   Team Date_Time    Series                    Ground
0   NaN            2nd Test            Lord's, London
1   NaN            3rd Test         Headingley, Leeds
2   NaN            4th Test          The Oval, London
3   NaN            5th Test  Old Trafford, Manchester

# 3.) Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/

In [9]:

driver = webdriver.Chrome("chromedriver.exe")
url="https://www.guru99.com/exception-handling-selenium.html"
driver.get(url)
exception=[]
description =[]
#scraping the exception 
ex=driver.find_elements_by_xpath("/html/body/div[2]/section[3]/div/div[1]/main/div[1]/div/div/div/div/div/div[2]/table/tbody/tr/td[1]")
for i in ex:
    if i.text is None :
        exception.append("--") 
    else:
        exception.append(i.text)
desc=driver.find_elements_by_xpath("/html/body/div[2]/section[3]/div/div[1]/main/div[1]/div/div/div/div/div/div[2]/table/tbody/tr/td[2]")
for i in desc:
    if i.text is None :
        description.append("--") 
    else:
        description.append(i.text)

selenium=pd.DataFrame([])
selenium['Exception']=exception
selenium['Description']=description

selenium

,Exception,Description
0,Exception name,Description
1,ElementNotVisibleException,This type of Selenium exception occurs when an...
2,ElementNotSelectableException,This Selenium exception occurs when an element...
3,NoSuchElementException,This Exception occurs if an element could not ...
4,NoSuchFrameException,This Exception occurs if the frame target to b...
5,NoAlertPresentException,This Exception occurs when you switch to no pr...
6,NoSuchWindowException,This Exception occurs if the window target to ...
7,StaleElementReferenceException,This Selenium exception occurs happens when th...
8,SessionNotFoundException,The WebDriver is acting after you quit the bro...
9,TimeoutException,Thrown when there is not enough time for a com...
10,WebDriverException,This Exception takes place when the WebDriver ...
11,ConnectionClosedException,This type of Exception takes place when there ...
12,ElementClickInterceptedException,The command may not be completed as the elemen...
13,ElementNotInteractableException,This Selenium exception is thrown when any ele...
14,ErrorInResponseException,This happens while interacting with the Firefo...
15,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
16,ImeActivationFailedException,This expectation will occur when IME engine ac...
17,ImeNotAvailableException,It takes place when IME support is unavailable.
18,InsecureCertificateException,Navigation made the user agent to hit a certif...
19,InvalidArgumentException,It occurs when an argument does not belong to ...
20,InvalidCookieDomainException,This happens when you try to add a cookie unde...
21,InvalidCoordinatesException,This type of Exception matches an interacting ...
22,InvalidElementStateExceptio,It occurs when command can't be finished when ...
23,InvalidSessionIdException,This Exception took place when the given sessi...
24,InvalidSwitchToTargetException,This occurs when the frame or window target to...
25,JavascriptException,This issue occurs while executing JavaScript g...
26,JsonException,It occurs when you afford to get the session w...
27,NoSuchAttributeException,This kind of Exception occurs when the attribu...
28,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
29,NoSuchContextException,ContextAware does mobile device testing.
30,NoSuchCookieException,This Exception occurs when no cookie matching ...
31,NotFoundException,This Exception is a subclass of WebDriverExcep...
32,RemoteDriverServerException,This Selenium exception is thrown when the ser...
33,ScreenshotException,It is not possible to capture a screen.
34,SessionNotCreatedException,It happens when a new session could not be suc...
35,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
36,UnexpectedTagNameException,Happens if a support class did not get a web e...
37,UnhandledAlertException,This expectation occurs when there is an alert...
38,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
39,UnknownMethodException,This Exception happens when the requested comm...
40,UnreachableBrowserException,This Exception occurs only when the browser is...
41,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

# 4.) Scrape the details of top 100 songs on billboard.com. Url = https://www.billboard.com/

In [27]:
driver = webdriver.Chrome(r"chromedriver.exe")
url="https://www.billboard.com/charts/hot-100"
driver.get(url)
time.sleep(5)

Song_Name =[]
Singer=[]
rank=[]
Last_Week=[]
Weeks_on_board=[]
#scraping the Rank 
rb=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
for i in rb:
    if i.text is None :
        rank.append("--") 
    else:
        rank.append(i.text)

#scraping the Song_Name 
son=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
for i in son:
    if i.text is None :
        Song_Name.append("--") 
    else:
        Song_Name.append(i.text)
#scraping the Singer 
sin=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
for i in sin:
    if i.text is None :
        Singer.append("--") 
    else:
        Singer.append(i.text)
#scraping the Last_Week Rank 
lwr=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
for i in lwr:
    if i.text is None :
        Last_Week.append("--") 
    else:
        Last_Week.append(i.text)
#scraping the Weeks_on_board 
wob=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
for i in wob:
    if i.text is None :
        Weeks_on_board.append("--") 
    else:
        Weeks_on_board.append(i.text)
BillBOARD_HOT100=pd.DataFrame([])
BillBOARD_HOT100['Peak_rank']=rank
BillBOARD_HOT100['Song_Name']=Song_Name
BillBOARD_HOT100['Singer / Crew']=Singer
BillBOARD_HOT100['Last_Week_Rank']=Last_Week
BillBOARD_HOT100['Weeks_on_board']=Weeks_on_board
BillBOARD_HOT100

,Peak_rank,Song_Name,Singer / Crew,Last_Week_Rank,Weeks_on_board
0,1,Butter,BTS,1,10
1,2,Industry Baby,Lil Nas X & Jack Harlow,-,1
2,1,Good 4 U,Olivia Rodrigo,2,11
3,3,Stay,The Kid LAROI & Justin Bieber,4,3
4,2,Levitating,Dua Lipa Featuring DaBaby,3,43
...,...,...,...,...,...
95,67,Minimum Wage,Blake Shelton,83,12
96,88,Working,Tate McRae X Khalid,-,5
97,50,Holy Smokes,Trippie Redd Featuring Lil Uzi Vert,50,2
98,14,WUSYANAME,"Tyler, The Creator Featuring YoungBoy Never Br...",91,5
99,100,Still Chose You,The Kid LAROI Featuring Mustard,-,1

# 5.) Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/

In [28]:
driver = webdriver.Chrome("chromedriver.exe")
url="https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(5)

Book_name=[]
Author_name=[]
Volumes_sold=[]
Publisher=[]
Genre=[]
#scraping the Book_name 
bname=driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[2]")
for i in bname:
    if i.text is None :
        Book_name.append("--") 
    else:
        Book_name.append(i.text)
#scraping the Author_name 
Auth=driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[3]")
for i in Auth:
    if i.text is None :
        Author_name.append("--") 
    else:
        Author_name.append(i.text)
#scraping the Genre 
gen=driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[6]")
for i in gen:
    if i.text is None :
        Genre.append("--") 
    else:
        Genre.append(i.text)

#scraping the Publisher 
pub=driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[5]")
for i in pub:
    if i.text is None :
        Publisher.append("--") 
    else:
        Publisher.append(i.text)
#scraping the Volumes_sold 
vs=driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[4]")
for i in vs:
    if i.text is None :
        Volumes_sold.append("--") 
    else:
        Volumes_sold.append(i.text)

Best_Books=pd.DataFrame([])
Best_Books['Book_name']=Book_name
Best_Books['Author_name']=Author_name
Best_Books['Genre']=Genre
Best_Books['Publisher']=Publisher
Best_Books['Volumes_sold']=Volumes_sold
Best_Books

,Book_name,Author_name,Genre,Publisher,Volumes_sold
0,"Da Vinci Code,The","Brown, Dan","Crime, Thriller & Adventure",Transworld,"5,094,805"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.",Children's Fiction,Bloomsbury,"4,475,152"
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.",Children's Fiction,Bloomsbury,"4,200,654"
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",Children's Fiction,Bloomsbury,"4,179,479"
4,Fifty Shades of Grey,"James, E. L.",Romance & Sagas,Random House,"3,758,936"
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert",General & Literary Fiction,Random House,"807,311"
96,Happy Days with the Naked Chef,"Oliver, Jamie",Food & Drink: General,Penguin,"794,201"
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne",Young Adult Fiction,Scholastic Ltd.,"792,187"
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave",Biography: General,Orion,"791,507"
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie",Food & Drink: General,Penguin,"791,095"

# 6.)Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455

In [30]:

driver = webdriver.Chrome("chromedriver.exe")
url="https://www.imdb.com/list/ls095964455"
driver.get(url)
time.sleep(5)

In [31]:
Name=[]
Year_span=[]
Genres=[]
Run_time=[]
Ratings=[]
Votes=[]
#scraping the Name 
mname=driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/a')
for i in mname:
    if i.text is None :
        Name.append("--") 
    else:
        Name.append(i.text)
#scraping the Year_span 
ys=driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']")
for i in ys:
    if i.text is None :
        Year_span.append("--") 
    else:
        Year_span.append(i.text)
#scraping the Genres 
gnr=driver.find_elements_by_xpath("//span[@class='genre']")
for i in gnr:
    if i.text is None :
        Genres.append("--") 
    else:
        Genres.append(i.text)
#scraping the Run_time 
rt=driver.find_elements_by_xpath("//span[@class='runtime']")
for i in rt[0:101]:
    if i.text is None :
        Run_time.append("--") 
    else:
        Run_time.append(i.text)
#scraping the Ratings 
rate=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
for i in rate:
    if i.text is None :
        Ratings.append("--") 
    else:
        Ratings.append(i.text)

#scraping the Votes 
v=driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]/span[2]")
for i in v:
    if i.text is None :
        Votes.append("--") 
    else:
        Votes.append(i.text)
        
IMDB_TOP_100_Series=pd.DataFrame([])
IMDB_TOP_100_Series['Name']=Name
IMDB_TOP_100_Series['Year_span']=Year_span
IMDB_TOP_100_Series['Run_time']=Run_time
IMDB_TOP_100_Series['Genres']=Genres
IMDB_TOP_100_Series['Ratings']=Ratings
IMDB_TOP_100_Series['Votes']=Votes
IMDB_TOP_100_Series

,Name,Year_span,Run_time,Genres,Ratings,Votes
0,Game of Thrones,(2011–2019),57 min,"Action, Adventure, Drama",9.2,"1,851,214"
1,Stranger Things,(2016– ),51 min,"Drama, Fantasy, Horror",8.7,"888,255"
2,The Walking Dead,(2010–2022),44 min,"Drama, Horror, Thriller",8.2,"887,068"
3,13 Reasons Why,(2017–2020),60 min,"Drama, Mystery, Thriller",7.6,"266,926"
4,The 100,(2014–2020),43 min,"Drama, Mystery, Sci-Fi",7.6,"227,292"
...,...,...,...,...,...,...
95,Reign,(2013–2017),42 min,"Drama, Fantasy",7.5,"45,123"
96,A Series of Unfortunate Events,(2017–2019),50 min,"Adventure, Comedy, Drama",7.8,"55,881"
97,Criminal Minds,(2005–2020),42 min,"Crime, Drama, Mystery",8,"172,190"
98,Scream: The TV Series,(2015–2019),45 min,"Comedy, Crime, Drama",7.1,"35,832"
99,The Haunting of Hill House,(2018),572 min,"Drama, Horror, Mystery",8.6,"195,559"

# 7.) Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/

In [33]:
driver = webdriver.Chrome("chromedriver.exe")
url="https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(5)

In [34]:
search_1 = driver.find_element_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a')       # Locating page foe top videos by xpath
search_1.click()

In [35]:
Dataset_Name=[]
Data_Type=[]
Task=[]
Attribute_Type=[]
No_of_Instances=[]
No_of_Attribute=[]
Year=[]


#scraping the Dataset_Name 
dname=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
for i in dname:
    if i.text is None :
        Dataset_Name.append("--") 
    else:
        Dataset_Name.append(i.text)
#scraping the Data_Type 
dtype=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
for i in dtype:
    if i.text is None :
        Data_Type.append("--") 
    else:
        Data_Type.append(i.text)

#scraping the Task 
t=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
for i in t:
    if i.text is None :
        Task.append("--") 
    else:
        Task.append(i.text)
#scraping the Attribute_Type 
att=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
for i in att:
    if i.text is None :
        Attribute_Type.append("--") 
    else:
        Attribute_Type.append(i.text)

#scraping the No_of_Instances 
noi=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
for i in noi:
    if i.text is None :
        No_of_Instances.append("--") 
    else:
        No_of_Instances.append(i.text)
#scraping the No_of_Attribute 
noa=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
for i in noa:
    if i.text is None :
        No_of_Attribute.append("--") 
    else:
        No_of_Attribute.append(i.text)
#scraping the Year 
y=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]/p")
for i in y:
    if i.text is None :
        Year.append("--") 
    else:
        Year.append(i.text)

UCI=pd.DataFrame([])
UCI['Dataset_Name']=Dataset_Name[:100]
UCI['Data_Type']=Data_Type[:100]
UCI['Task']=Task[:100]
UCI['Attribute_Type']=Attribute_Type[:100]
UCI['No_of_Instances']=No_of_Instances[:100]
UCI['No_of_Attribute']=No_of_Attribute[:100]
UCI['Year']=Year[:100]
UCI

,Dataset_Name,Data_Type,Task,Attribute_Type,No_of_Instances,No_of_Attribute,Year
0,Abalone,Data Types,Default Task,Attribute Types,# Instances,# Attributes,Year
1,Adult,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Annealing,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Anonymous Microsoft Web Data,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Arrhythmia,,Recommender-Systems,Categorical,37711,294,1998
...,...,...,...,...,...,...,...
95,Statlog Project,Multivariate,Clustering,"Categorical, Integer",76,45,
96,Student Loan Relational,,,,,,1992
97,Teaching Assistant Evaluation,Domain-Theory,,,1000,,1993
98,Tic-Tac-Toe Endgame,Multivariate,Classification,"Categorical, Integer",151,5,1997
99,Thyroid Disease,Multivariate,Classification,Categorical,958,9,1991

In [36]:
UCI.to_csv('UCI_datasets.csv')